// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alfnngetdsxwsvldvzpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsZm5uZ2V0ZHN4d3N2bGR2enBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzE5MjcsImV4cCI6MjA2OTAwNzkyN30.61ioddBFpoZ2j2K_Z8KKajKOe8nnY0JzjhF6Yy4MmJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});